#!/usr/bin/env python3
"""
ali_send.py

職責（修正版，請務必閱讀）：
- 將 LLM 產生的「內部審查用 reply body」包裝成一封 email
- 僅允許回覆給「forward 這封郵件的工程師本人」
- 嚴格禁止在任何情況下直接回覆原始客戶或第三方
- 經由 SMTP 寄出，並：
  - 將已寄信寫入 IMAP Sent
  - 將原始郵件標記為已讀

⚠️ 安全原則（不可破壞）：
- ALI 永遠不是對外發信者
- ALI 只是一個「工程判斷草稿生成器」
- 任何對客戶的回信，必須由工程師本人手動發送
"""

from __future__ import annotations

import smtplib
from email.message import EmailMessage as StdEmailMessage
from email.utils import parseaddr
from typing import Optional

from helper.utils_config import load_env, configure_logging  # type: ignore
from helper.utils_imap_config import load_smtp_config  # type: ignore
from helper.utils_imap_types import EmailMessage, SendResult  # type: ignore
from helper.utils_imap_ops import append_to_imap_sent  # type: ignore


# ------------------------------------------------------------
# Safety guard: ONLY reply to forward sender
# ------------------------------------------------------------

def _require_reply_to_forward_sender(original_from: str, to_addr: str) -> None:
    """
    Hard safety guard.

    Enforces that ALI can ONLY reply to the email-sender who forwarded the email.
    Comparison is done on the actual email address (addr-spec),
    NOT on the display name.
    """
    if not original_from or not to_addr:
        raise RuntimeError("Missing sender or recipient address")

    _, original_email = parseaddr(original_from)
    _, to_email = parseaddr(to_addr)

    if not original_email or not to_email:
        raise RuntimeError(
            f"Unable to parse email address: "
            f"from={original_from}, to={to_addr}"
        )

    if original_email.strip().lower() != to_email.strip().lower():
        raise RuntimeError(
            f"Illegal recipient blocked: {to_email}. "
            f"Only forward sender {original_email} is allowed."
        )


# ------------------------------------------------------------
# Build outgoing message
# ------------------------------------------------------------

def _build_subject(original_subject: str) -> str:
    if not original_subject:
        return "Re:"
    lower = original_subject.lstrip().lower()
    if lower.startswith("re:"):
        return original_subject
    return f"Re: {original_subject}"


def _build_to_address(from_header: str) -> str:
    """
    Resolve the reply target from original From header.

    In forward-to-ALI workflow, original.from_addr MUST be the email-sender,
    not the customer.
    """
    name, addr = parseaddr(from_header)
    return addr or from_header or ""


def _build_message(
    original: EmailMessage,
    reply_body: str,
    from_addr: str,
) -> StdEmailMessage:
    msg = StdEmailMessage()
    msg["From"] = from_addr

    # IMPORTANT:
    # This resolves to the forward sender, NOT the customer.
    to_addr = _build_to_address(original.from_addr)
    msg["To"] = to_addr

    subject = _build_subject(original.subject)
    msg["Subject"] = subject

    if original.message_id:
        msg["In-Reply-To"] = original.message_id
        msg["References"] = original.message_id

    base_body = (reply_body or "").rstrip()
    original_body = (original.body_text or "").strip()

    if original_body:
        header_lines = []
        if original.from_addr:
            header_lines.append(f"From: {original.from_addr}")
        if original.to_addrs:
            header_lines.append(f"To: {', '.join(original.to_addrs)}")
        if original.subject:
            header_lines.append(f"Subject: {original.subject}")

        header_block = ""
        if header_lines:
            header_block = "-----Original Message-----\n" + "\n".join(header_lines)

        quoted_lines = []
        for line in original_body.splitlines():
            quoted_lines.append(f"> {line}" if line.strip() else ">")
        quoted_block = "\n".join(quoted_lines)

        history_block = (
            f"{header_block}\n\n{quoted_block}" if header_block else quoted_block
        )

        full_body = f"{base_body}\n\n{history_block}" if base_body else history_block
    else:
        full_body = base_body

    msg.set_content(full_body, subtype="plain", charset="utf-8")
    return msg


# ------------------------------------------------------------
# Public API: send_reply (EMAIL-SENDER-ONLY)
# ------------------------------------------------------------

def send_reply(
    original: EmailMessage,
    reply_body: str,
    *,
    from_addr: Optional[str] = None,
) -> SendResult:
    """
    Send INTERNAL review email to email-sender only.

    Parameters:
    - original:
        The forwarded EmailMessage.
        original.from_addr MUST be the email-sender who forwarded the email.
    - reply_body:
        Internal review content generated by ALI (NOT customer-ready).
    - from_addr:
        Optional sender override; defaults to SMTP configured identity.

    Any attempt to reply to non-forward-sender will be blocked.
    """
    load_env()
    logger = configure_logging("ali_email_sender")

    smtp_cfg = load_smtp_config()
    if smtp_cfg is None:
        return SendResult(ok=False, error_message="Missing SMTP_HOST/USER/PASSWORD")

    sender = from_addr or smtp_cfg.default_from
    msg = _build_message(original, reply_body, sender)
    msg["Reply-To"] = smtp_cfg.user

    # ---- HARD SAFETY CHECK (non-negotiable) ----
    _require_reply_to_forward_sender(original.from_addr, msg["To"])

    try:
        if smtp_cfg.use_ssl:
            server: smtplib.SMTP = smtplib.SMTP_SSL(
                smtp_cfg.host, smtp_cfg.port, timeout=60
            )
        else:
            server = smtplib.SMTP(smtp_cfg.host, smtp_cfg.port, timeout=60)

        with server:
            server.ehlo()
            if not smtp_cfg.use_ssl and smtp_cfg.use_starttls:
                server.starttls()
                server.ehlo()
            server.login(smtp_cfg.user, smtp_cfg.password)
            server.send_message(msg)

        logger.info(
            "Sent INTERNAL review to %s (uid=%s)",
            msg["To"],
            original.uid,
        )

        # Write to IMAP Sent (best-effort)
        append_to_imap_sent(msg, logger)

        return SendResult(ok=True)
    except Exception as exc:
        logger.error("Failed to send internal review for uid=%s: %s", original.uid, exc)
        return SendResult(ok=False, error_message=str(exc))
